In [1]:
import pandas as pd
import ast
import sys
import os
import numpy as np

In [2]:
from server_config import DATA_PATH
sys.path.append(os.path.abspath("functions"))

### 1. Therapist data

In [3]:
df_th = pd.read_csv(DATA_PATH + "/df_th_nopr_experience_corrected_200624_LB.csv", sep=";",low_memory = "False")

In [4]:
keep_cols_th = ['therapist_id', 'u_registrationDate_t','t0_method_t_CBT','t0_method_t_PDT','t0_method_t_ST','t0_method_t_AP', 't0_appliedmethod_t_VT', 't0_appliedmethod_t_TP',
             't0_appliedmethod_t_AP', 't0_appliedmethod_t_ST','t0_appliedmethod_t_Other','t0_location_t','t0_gender_t',
 't0_relationship_t','t0_sexualorientation_t','t0_children_t','t0_age_t', 't0_experience_t','t0_license_t', 't0_bfi_t_1',
 't0_bfi_t_2','t0_bfi_t_3','t0_bfi_t_4','t0_bfi_t_5','t0_bfi_t_6','t0_bfi_t_7','t0_bfi_t_8','t0_bfi_t_9','t0_bfi_t_10',]

In [5]:
labels = ["VT", "TP", "AP", "ST", "Other"]  

col = df_th["t0_appliedmethod_t_A"]

# 1) Parse strings like "[True, False, ...]" -> list
col = col.map(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# 2) Unwrap nested lists like [[True, False, ...]] -> [True, False, ...]
col = col.map(lambda x: x[0] if isinstance(x, (list, tuple)) and len(x) == 1 and isinstance(x[0], (list, tuple)) else x)

# 3) Safety: replace missing/invalid with all-False (or raise if you prefer)
def ensure_five(x):
    if isinstance(x, (list, tuple)) and len(x) == 5:
        return list(x)
    if pd.isna(x):
        return [False]*5

col = col.map(ensure_five)

# 4) Build the indicator columns
method_df = (
    pd.DataFrame(col.tolist(), index=df_th.index, columns=labels)
      .astype(int)
      .add_prefix("t0_appliedmethod_t_")
)

In [6]:
df_th = df_th.join(method_df)

In [7]:
df_th = df_th[keep_cols_th]

In [8]:
# BFI-10 items (1–5), reverse-code, then build subscale SUMS using df_th and t0-prefix
bfi_items = [f"t0_bfi_t_{i}" for i in range(1, 11)]
df_th[bfi_items] = df_th[bfi_items].apply(pd.to_numeric, errors="coerce")


# Subscale sums (2 items each)
df_th["t0_bfi_t_extraversion"]     = df_th[["t0_bfi_t_1", "t0_bfi_t_6"]].sum(axis=1)
df_th["t0_bfi_t_agreeableness"]    = df_th[["t0_bfi_t_2",   "t0_bfi_t_7"]].sum(axis=1)
df_th["t0_bfi_t_conscientiousness"]= df_th[["t0_bfi_t_3", "t0_bfi_t_8"]].sum(axis=1)
df_th["t0_bfi_t_neuroticism"]      = df_th[["t0_bfi_t_4", "t0_bfi_t_9"]].sum(axis=1)
df_th["t0_bfi_t_openness"]         = df_th[["t0_bfi_t_5", "t0_bfi_t_10"]].sum(axis=1)

### 2. Patient data

In [9]:
df_pat = pd.read_json(DATA_PATH + "/TONI_pat_corrected_20241025_raw.json")

In [10]:
keep_cols = (
    # IDs / study
    ['patient_id', 'therapist_id', 'u_registrationDate_p'] +

    # Demographics / baseline
    ['t0_age_p','t0_gender_p','t0_school_p','t0_employment_p','t0_location_p'] +
    [f"t0_therapy_p_{i}" for i in range(1, 4)] +
    ['t0_familyhistory_p','t0_meds_p','t0_relationship_p','t0_ses_p'] +
    [f"t0_migration_p_{i}" for i in range(1, 4)] +
    [f"surveys.t0.answers.1585.discrimination_{i}" for i in range(1, 6)] +
    [f"t0_disease_p_{c}" for c in list('ABCDEFG')] +

    # t0 scales
    [f"t0_phq_p_{i}" for i in range(1, 9)] +
    [f"t0_gad_p_{i}" for i in range(1, 7+1)] +
    [f"t0_swls_p_{i}" for i in range(1, 5+1)] +
    [f"t0_aqol_p_{i}" for i in range(1, 35+1)] +
    [f"t0_ede_p_{i}" for i in range(1, 8+1)] +
    (['t0_audit_p_filter'] + [f"t0_audit_p_{i}" for i in range(1, 3+1)]) +
    (['t0_dudit_p_filter'] + [f"t0_dudit_p_{i}" for i in range(1, 4+1)]) +
    [f"t0_msfq_p_{i}" for i in range(1, 5+1)] +
    [f"t0_pid_p_{i}" for i in range(1, 36+1)] +
    [f"t0_opd_p_{i}" for i in range(1, 12+1)] +
    [f"t0_ace_p_{i}" for i in range(1, 10+1)] +
    [f"t0_ask_p_{i}" for i in range(1, 3+1)] +
    [f"t0_mhse_p_{i}" for i in range(1, 6+1)] +

    # t1 scales
    [f"t1_phq_p_{i}" for i in range(1, 8+1)] +
    [f"t1_gad_p_{i}" for i in range(1, 7+1)] +
    [f"t1_multi_p_{i}" for i in range(1, 7+1)] +
    [f"t1_cpps_p_{i}" for i in range(1, 20+1)] +

    # t2 scales
    [f"t2_phq_p_{i}" for i in range(1, 8+1)] +
    [f"t2_gad_p_{i}" for i in range(1, 7+1)] +

    
    # t3 scales
    [f"t3_phq_p_{i}" for i in range(1, 8+1)] +
    [f"t3_gad_p_{i}" for i in range(1, 7+1)] +


    # alliance / matching

    [ 't0_change_p_1', 't0_change_p_2', 't0_dropout_p']
)

In [11]:
df_pat= df_pat[keep_cols]

#### 2.1 Calculate Subscales for self-report data

#### Outcome (PHQ + GAD)

In [12]:
# define item columns
phq_cols_t1 = [f"t1_phq_p_{i}" for i in range(1, 9)]
gad_cols_t1 = [f"t1_gad_p_{i}" for i in range(1, 8)]

mask_complete = df_pat[phq_cols_t1 + gad_cols_t1].notna().all(axis=1)
df_pat_clean = df_pat.loc[mask_complete].copy()

In [13]:
df_pat_clean["t1_phq8_total"] = df_pat_clean[phq_cols_t1].sum(axis=1)
df_pat_clean["t1_gad7_total"] = df_pat_clean[gad_cols_t1].sum(axis=1)

In [14]:
df_pat_clean["t1_distress_sum"] = (
    df_pat_clean["t1_phq8_total"] + df_pat_clean["t1_gad7_total"]
)

In [15]:
# define item columns
phq_cols_t0 = [f"t0_phq_p_{i}" for i in range(1, 9)]
gad_cols_t0 = [f"t0_gad_p_{i}" for i in range(1, 8)]

In [16]:
df_pat_clean["t0_phq8_p_sum"] = df_pat_clean[phq_cols_t0].sum(axis=1)
df_pat_clean["t0_gad7_p_sum"] = df_pat_clean[gad_cols_t0].sum(axis=1)

In [17]:
df_pat_clean["t0_distress_sum"] = (
    df_pat_clean["t0_phq8_p_sum"] + df_pat_clean["t0_gad7_p_sum"]
)

In [18]:
df_pat_clean["change_distress"] =  (df_pat_clean["t0_distress_sum"] - df_pat_clean["t1_distress_sum"])/df_pat_clean["t0_distress_sum"]*100

In [19]:
df_pat_clean = df_pat_clean.loc[df_pat_clean.change_distress.notna()]

#### SWLS Baseline

In [20]:
swls_cols_t0 = [f"t0_swls_p_{i}" for i in range(1, 6)]

In [21]:
df_pat_clean["t0_swls_p_sum"] = df_pat_clean[swls_cols_t0].sum(axis=1)

#### Aqol Baseline

In [22]:
aqol_map = {
    "t0_aqol_p_coping": ['t0_aqol_p_1', 't0_aqol_p_21', 't0_aqol_p_29'],
    "t0_aqol_p_relationship": ['t0_aqol_p_2', 't0_aqol_p_4', 't0_aqol_p_9', 't0_aqol_p_10',
                               't0_aqol_p_23', 't0_aqol_p_31', 't0_aqol_p_34'],
    "t0_aqol_p_independent_living": ['t0_aqol_p_3', 't0_aqol_p_15', 't0_aqol_p_19', 't0_aqol_p_30'],
    "t0_aqol_p_mental_health": ['t0_aqol_p_5', 't0_aqol_p_8', 't0_aqol_p_12', 't0_aqol_p_14',
                                't0_aqol_p_16', 't0_aqol_p_18', 't0_aqol_p_33', 't0_aqol_p_35'],
    "t0_aqol_p_pain": ['t0_aqol_p_6', 't0_aqol_p_22', 't0_aqol_p_24'],
    "t0_aqol_p_self_worth": ['t0_aqol_p_7', 't0_aqol_p_13', 't0_aqol_p_26'],
    "t0_aqol_p_happiness": ['t0_aqol_p_17', 't0_aqol_p_20', 't0_aqol_p_25', 't0_aqol_p_27'],
    "t0_aqol_p_senses": ['t0_aqol_p_11', 't0_aqol_p_28', 't0_aqol_p_32'],
}

In [23]:
df_pat_clean = df_pat_clean.assign(**{scale: df_pat_clean[items].mean(axis=1) for scale, items in aqol_map.items()})

#### EDE Baseline

In [24]:
df_pat_clean["t0_ede_p_sum"] = df_pat_clean[[f"t0_ede_p_{i}" for i in range(1, 9)]].sum(axis=1)

#### Audit Baseline

In [25]:
aud_items = [f"t0_audit_p_{i}" for i in range(1, 5)]
fcol = "t0_audit_p_filter"

# set all AUDIT item columns to 0 if filter == 0
df_pat_clean.loc[df_pat_clean[fcol].eq(0), aud_items] = 0

# sum AUDIT items only if filter == 1; otherwise set total to 0
df_pat_clean["t0_audit_p_sum"] = np.where(
    df_pat_clean[fcol].eq(1),
    df_pat_clean[aud_items].sum(axis=1),
    0
)

#### Dudit Baseline

In [26]:
dud_items = [f"t0_dudit_p_{i}" for i in range(1, 5)]
fcol = "t0_dudit_p_filter"

# set all AUDIT item columns to 0 if filter == 0
df_pat_clean.loc[df_pat_clean[fcol].eq(0), dud_items] = 0

# sum AUDIT items only if filter == 1; otherwise set total to 0
df_pat_clean["t0_dudit_p_sum"] = np.where(
    df_pat_clean[fcol].eq(1),
    df_pat_clean[dud_items].sum(axis=1),
    0
)

#### MFSQ Baseline

In [27]:
msfq_cols = [f"t0_msfq_p_{i}" for i in range(1, 6)]
df_pat_clean[msfq_cols] = df_pat_clean[msfq_cols].apply(pd.to_numeric, errors="coerce")

df_pat_clean["t0_msfq_p_sum"] = df_pat_clean[msfq_cols].sum(axis=1)

#### PID5BF+ Baseline

In [28]:

# PID-5 BF+ domains → item columns
pid_map = {
    "t0_pid_p_negative_affect": ['t0_pid_p_1','t0_pid_p_7','t0_pid_p_13','t0_pid_p_19','t0_pid_p_25','t0_pid_p_31'],
    "t0_pid_p_antagonism":      ['t0_pid_p_2','t0_pid_p_8','t0_pid_p_14','t0_pid_p_20','t0_pid_p_26','t0_pid_p_32'],
    "t0_pid_p_disinhibition":   ['t0_pid_p_3','t0_pid_p_9','t0_pid_p_15','t0_pid_p_21','t0_pid_p_27','t0_pid_p_33'],
    "t0_pid_p_detachment":      ['t0_pid_p_4','t0_pid_p_10','t0_pid_p_16','t0_pid_p_22','t0_pid_p_28','t0_pid_p_34'],
    "t0_pid_p_psychoticism":    ['t0_pid_p_5','t0_pid_p_11','t0_pid_p_17','t0_pid_p_23','t0_pid_p_29','t0_pid_p_35'],
    "t0_pid_p_anankastia":      ['t0_pid_p_6','t0_pid_p_12','t0_pid_p_18','t0_pid_p_24','t0_pid_p_30','t0_pid_p_36'],
}

# 1) Coerce all PID item columns to numeric (e.g., "2" → 2, invalid → NaN)
item_cols = sorted({c for cols in pid_map.values() for c in cols})
df_pat_clean[item_cols] = df_pat_clean[item_cols].apply(pd.to_numeric, errors="coerce")

# 2) Domain sums (NaNs treated as 0 by default)
for scale, items in pid_map.items():
    df_pat_clean[scale] = df_pat_clean[items].mean(axis=1)

#### OPD Baseline

In [29]:
# OPD-SFK domains → item columns
opd_map = {
    "t0_opd_p_self":         ['t0_opd_p_1', 't0_opd_p_2', 't0_opd_p_5', 't0_opd_p_8'],
    "t0_opd_p_contact":      ['t0_opd_p_4', 't0_opd_p_6', 't0_opd_p_10', 't0_opd_p_11'],
    "t0_opd_p_relationship": ['t0_opd_p_3', 't0_opd_p_7', 't0_opd_p_9', 't0_opd_p_12'],
}

# coerce item columns to numeric (e.g., "2" → 2; invalid → NaN)
opd_items = sorted({c for cols in opd_map.values() for c in cols})
df_pat_clean[opd_items] = df_pat_clean[opd_items].apply(pd.to_numeric, errors="coerce")

# domain sums (NaNs treated as 0 by default)
for scale, items in opd_map.items():
    df_pat_clean[scale] = df_pat_clean[items].mean(axis=1)

#### ACE Baseline

In [30]:
ace_cols = [f"t0_ace_p_{i}" for i in range(1, 11)]

# ensure numeric (e.g., "1" -> 1; invalid -> NaN)
df_pat_clean[ace_cols] = df_pat_clean[ace_cols].apply(pd.to_numeric, errors="coerce")

df_pat_clean["t0_ace_p_sum"] = df_pat_clean[ace_cols].sum(axis=1)

/tmp/ipykernel_3481552/1448277295.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_pat_clean["t0_ace_p_sum"] = df_pat_clean[ace_cols].sum(axis=1)

#### ASK Baseline

In [31]:
ask_cols = [f"t0_ask_p_{i}" for i in range(1, 4)]
df_pat_clean[ask_cols] = df_pat_clean[ask_cols].apply(pd.to_numeric, errors="coerce")

df_pat_clean["t0_ask_p_sum"] = df_pat_clean[ask_cols].sum(axis=1)

/tmp/ipykernel_3481552/3480057311.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_pat_clean["t0_ask_p_sum"] = df_pat_clean[ask_cols].sum(axis=1)

#### MHSE Baseline

In [32]:
mhse_cols = [f"t0_mhse_p_{i}" for i in range(1, 7)]
df_pat_clean[mhse_cols] = df_pat_clean[mhse_cols].apply(pd.to_numeric, errors="coerce")

df_pat_clean["t0_mhse_p_sum"] = df_pat_clean[mhse_cols].sum(axis=1)

/tmp/ipykernel_3481552/913225046.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_pat_clean["t0_mhse_p_sum"] = df_pat_clean[mhse_cols].sum(axis=1)

#### Multi T1

In [33]:
# define the 7 MULTI item columns once
multi_cols = [f"t1_multi_p_{i}" for i in range(1, 8)]

# 1) ensure the same columns are numeric
df_pat_clean[multi_cols] = df_pat_clean[multi_cols].apply(pd.to_numeric, errors="coerce")

# 2) compute therapist-level means and attach as 7 new columns to every row
multi_avg = (
    df_pat_clean
    .groupby("therapist_id")[multi_cols]
    .transform("mean")
)
multi_avg.columns = [c.replace("t1_multi_p_", "multi_avg_") for c in multi_avg.columns]

# 3) append to your dataframe (now you have multi_avg_1 .. multi_avg_7)
df_pat_clean = pd.concat([df_pat_clean, multi_avg], axis=1)
df_pat_clean["multi_sum"] = df_pat_clean[["multi_avg_1", "multi_avg_2", "multi_avg_3", "multi_avg_4", "multi_avg_5","multi_avg_6","multi_avg_7"]].sum(axis=1)

#### CPPS

In [34]:
cpps_cols = [f"t1_cpps_p_{i}" for i in range(1, 21)]

df_pat_clean[cpps_cols] = df_pat_clean[cpps_cols].apply(pd.to_numeric, errors="coerce")
cpps_avg = (
    df_pat_clean
    .groupby("therapist_id")[cpps_cols]
    .transform("mean"))
cpps_avg.columns = [c.replace("t1_cpps_p_", "cpps_avg_") for c in cpps_avg.columns]
df_pat_clean = pd.concat([df_pat_clean, cpps_avg], axis=1)

df_pat_clean["tx_cpps_p_pd"] = df_pat_clean[['cpps_avg_1', 'cpps_avg_4', 'cpps_avg_5', 'cpps_avg_7',
'cpps_avg_8', 'cpps_avg_10', 'cpps_avg_13', 'cpps_avg_14', 'cpps_avg_16', 'cpps_avg_19']].sum(axis=1)

df_pat_clean["tx_cpps_p_vt"] = df_pat_clean[['cpps_avg_2', 'cpps_avg_3', 'cpps_avg_6', 'cpps_avg_9',
'cpps_avg_11', 'cpps_avg_12', 'cpps_avg_15', 'cpps_avg_17', 'cpps_avg_18', 'cpps_avg_20']].sum(axis=1)

### Intake

### Concatenate patient and therapist df

In [35]:
df_all = pd.merge(df_pat_clean, df_th, on="therapist_id", how= "left", validate = "many_to_one")

In [36]:
df_all["u_registrationDate_p_datetime"] = pd.to_datetime(
    df_all["u_registrationDate_p"], errors="coerce", dayfirst=True, utc=True
)
iso = df_all["u_registrationDate_p_datetime"].dt.isocalendar()
df_all["intake_week"]  = iso.week.astype("Int64")
df_all["intake_month"] = df_all["u_registrationDate_p_datetime"].dt.month.astype("Int64")
df_all["intake_year"]  = df_all["u_registrationDate_p_datetime"].dt.year.astype("Int64").astype("string")

In [37]:
patient_numeric=['t0_age_p', 't0_ses_p', 'surveys.t0.answers.1585.discrimination_1', 'surveys.t0.answers.1585.discrimination_2',
 'surveys.t0.answers.1585.discrimination_3', 'surveys.t0.answers.1585.discrimination_4', 'surveys.t0.answers.1585.discrimination_5',
  't0_phq_p_1', 't0_phq_p_2', 't0_phq_p_3', 't0_phq_p_4', 't0_phq_p_5', 't0_phq_p_6', 't0_phq_p_7', 't0_phq_p_8',
 't0_gad_p_1', 't0_gad_p_2', 't0_gad_p_3', 't0_gad_p_4', 't0_gad_p_5', 't0_gad_p_6', 't0_gad_p_7','t0_swls_p_1',
 't0_swls_p_2', 't0_swls_p_3', 't0_swls_p_4', 't0_swls_p_5', 't0_aqol_p_1','t0_aqol_p_2', 't0_aqol_p_3',
 't0_aqol_p_4', 't0_aqol_p_5', 't0_aqol_p_6', 't0_aqol_p_7', 't0_aqol_p_8', 't0_aqol_p_9', 't0_aqol_p_10',
 't0_aqol_p_11', 't0_aqol_p_12', 't0_aqol_p_13', 't0_aqol_p_14', 't0_aqol_p_15', 't0_aqol_p_16', 't0_aqol_p_17',
 't0_aqol_p_18', 't0_aqol_p_19', 't0_aqol_p_20', 't0_aqol_p_21', 't0_aqol_p_22', 't0_aqol_p_23', 't0_aqol_p_24',
 't0_aqol_p_25', 't0_aqol_p_26', 't0_aqol_p_27', 't0_aqol_p_28', 't0_aqol_p_29', 't0_aqol_p_30', 't0_aqol_p_31',
 't0_aqol_p_32', 't0_aqol_p_33', 't0_aqol_p_34', 't0_aqol_p_35', 't0_audit_p_1', 't0_audit_p_2', 't0_audit_p_3',
  't0_dudit_p_1', 't0_dudit_p_2', 't0_dudit_p_3', 't0_dudit_p_4', 't0_msfq_p_1', 't0_msfq_p_2', 't0_msfq_p_3',
 't0_msfq_p_4', 't0_msfq_p_5', 't0_pid_p_1', 't0_pid_p_2', 't0_pid_p_3', 't0_pid_p_4', 't0_pid_p_5', 't0_pid_p_6',
 't0_pid_p_7', 't0_pid_p_8', 't0_pid_p_9', 't0_pid_p_10', 't0_pid_p_11', 't0_pid_p_12', 't0_pid_p_13', 't0_pid_p_14',
 't0_pid_p_15', 't0_pid_p_16', 't0_pid_p_17', 't0_pid_p_18', 't0_pid_p_19', 't0_pid_p_20', 't0_pid_p_21',
 't0_pid_p_22', 't0_pid_p_23', 't0_pid_p_24', 't0_pid_p_25', 't0_pid_p_26', 't0_pid_p_27', 't0_pid_p_28',
 't0_pid_p_29', 't0_pid_p_30', 't0_pid_p_31', 't0_pid_p_32', 't0_pid_p_33', 't0_pid_p_34', 't0_pid_p_35',
 't0_pid_p_36', 't0_opd_p_1', 't0_opd_p_2', 't0_opd_p_3', 't0_opd_p_4', 't0_opd_p_5', 't0_opd_p_6', 't0_opd_p_7',
 't0_opd_p_8', 't0_opd_p_9', 't0_opd_p_10', 't0_opd_p_11', 't0_opd_p_12', 't0_ace_p_1', 't0_ace_p_2',
 't0_ace_p_3', 't0_ace_p_4', 't0_ace_p_5', 't0_ace_p_6', 't0_ace_p_7', 't0_ace_p_8', 't0_ace_p_9', 't0_ace_p_10',
 't0_ask_p_1', 't0_ask_p_2', 't0_ask_p_3', 't0_mhse_p_1', 't0_mhse_p_2', 't0_mhse_p_3', 't0_mhse_p_4', 't0_mhse_p_5',
 't0_mhse_p_6', 't0_change_p_1', 't0_change_p_2', 't0_dropout_p', 't0_phq8_p_sum', 't0_gad7_p_sum', 't0_swls_p_sum',
 't0_aqol_p_coping','t0_aqol_p_relationship', 't0_aqol_p_independent_living', 't0_aqol_p_mental_health',
 't0_aqol_p_pain', 't0_aqol_p_self_worth', 't0_aqol_p_happiness', 't0_aqol_p_senses', 't0_audit_p_sum',
 't0_dudit_p_sum', 't0_msfq_p_sum', 't0_pid_p_negative_affect', 't0_pid_p_antagonism', 't0_pid_p_disinhibition',
 't0_pid_p_detachment', 't0_pid_p_psychoticism', 't0_pid_p_anankastia', 't0_opd_p_self', 't0_opd_p_contact',
 't0_opd_p_relationship', 't0_ace_p_sum', 't0_ask_p_sum', 't0_mhse_p_sum']

patient_categorical=['t0_gender_p', 't0_school_p', 't0_employment_p', 't0_location_p', 't0_therapy_p_1', 't0_therapy_p_2',
 't0_therapy_p_3', 't0_familyhistory_p', 't0_meds_p', 't0_relationship_p', 't0_migration_p_1',
 't0_migration_p_2', 't0_migration_p_3', 't0_disease_p_A', 't0_disease_p_B', 't0_disease_p_C',
 't0_disease_p_D', 't0_disease_p_E', 't0_disease_p_F', 't0_disease_p_G']

In [38]:
miss_summary = (df_all[patient_numeric + patient_categorical]
                .isna()
                .sum()
                .rename("n_nan")
                .to_frame())
miss_summary["pct_nan"] = miss_summary["n_nan"] / len(df_all) * 100
miss_summary.sort_values("pct_nan", ascending=False).head(20)

                n_nan    pct_nan
t0_therapy_p_3    459  47.564767
t0_pid_p_23       309  32.020725
t0_pid_p_25       309  32.020725
t0_pid_p_26       309  32.020725
t0_pid_p_27       309  32.020725
t0_pid_p_24       309  32.020725
t0_pid_p_33       309  32.020725
t0_pid_p_30       309  32.020725
t0_pid_p_31       309  32.020725
t0_pid_p_32       309  32.020725
t0_pid_p_20       309  32.020725
t0_pid_p_21       309  32.020725
t0_pid_p_35       309  32.020725
t0_pid_p_28       309  32.020725
t0_pid_p_29       309  32.020725
t0_pid_p_22       309  32.020725
t0_pid_p_19       309  32.020725
t0_pid_p_36       309  32.020725
t0_pid_p_34       309  32.020725
t0_pid_p_18       279  28.911917

In [39]:
therapist_numeric = [
        't0_age_t','t0_experience_t','t0_bfi_t_1','t0_bfi_t_2','t0_bfi_t_3','t0_bfi_t_4','t0_bfi_t_5',
        't0_bfi_t_6','t0_bfi_t_7','t0_bfi_t_8','t0_bfi_t_9','t0_bfi_t_10',
        't0_bfi_t_extraversion','t0_bfi_t_agreeableness','t0_bfi_t_conscientiousness',
        't0_bfi_t_neuroticism','t0_bfi_t_openness'
    ]
therapist_categorical = [
        't0_method_t_CBT','t0_method_t_PDT','t0_method_t_ST','t0_method_t_AP',
        't0_appliedmethod_t_VT','t0_appliedmethod_t_TP','t0_appliedmethod_t_AP',
        't0_appliedmethod_t_ST','t0_appliedmethod_t_Other',
        't0_location_t','t0_gender_t','t0_relationship_t','t0_sexualorientation_t','t0_children_t'
    ]

In [40]:
miss_summary = (df_all[therapist_numeric + therapist_categorical]
                .isna()
                .sum()
                .rename("n_nan")
                .to_frame())
miss_summary["pct_nan"] = miss_summary["n_nan"] / len(df_all) * 100
miss_summary.sort_values("pct_nan", ascending=False).head(20)

                            n_nan   pct_nan
t0_age_t                        9  0.932642
t0_experience_t                 9  0.932642
t0_bfi_t_1                      9  0.932642
t0_bfi_t_2                      9  0.932642
t0_bfi_t_3                      9  0.932642
t0_bfi_t_4                      9  0.932642
t0_bfi_t_5                      9  0.932642
t0_bfi_t_6                      9  0.932642
t0_bfi_t_7                      9  0.932642
t0_bfi_t_8                      9  0.932642
t0_bfi_t_9                      9  0.932642
t0_bfi_t_10                     9  0.932642
t0_sexualorientation_t          9  0.932642
t0_relationship_t               9  0.932642
t0_gender_t                     9  0.932642
t0_location_t                   9  0.932642
t0_children_t                   9  0.932642
t0_bfi_t_extraversion           8  0.829016
t0_bfi_t_agreeableness          8  0.829016
t0_bfi_t_conscientiousness      8  0.829016

#### Remove therapists with missing side features

In [41]:
df_all = df_all[df_all.t0_experience_t.notna()]

In [42]:
df_all.therapist_id.nunique()

174

In [43]:
df_all.patient_id.nunique()

956

#### Mark age as missing

In [44]:
mask_bad_age = df_all["t0_age_t"].notna() & (df_all["t0_age_t"] < 23)
n_bad = int(mask_bad_age.sum())
print(f"[repair] t0_age_t: setting {n_bad} implausible values (<23) to NaN")

df_all.loc[mask_bad_age, "t0_age_t"] = np.nan

[repair] t0_age_t: setting 92 implausible values (<23) to NaN

In [ ]:
def fix_therapist_age_simple(
    df: pd.DataFrame,
    *,
    age_col: str = "t0_age_t",
    license_year_col: str = "t0_license_t",      # YYYY
    reg_date_col: str = "u_registrationDate_t",  # date/datetime/str
    min_age_at_license: int = 26,                # set manually
    min_age_global: int = 23,                    # absolute floor
    max_age_global: int = 80,
    out_col: str = "t0_age_t_fixed_emp"
) -> pd.Series:
    # parse inputs
    age = pd.to_numeric(df.get(age_col), errors="coerce")
    lic = pd.to_numeric(df.get(license_year_col), errors="coerce")
    reg = pd.to_datetime(df.get(reg_date_col), errors="coerce")
    reg_year = reg.dt.year

    # years since license (negatives → 0; missing → 0 for a conservative floor)
    yrs_since_lic = (reg_year - lic).where(lic.notna() & reg_year.notna(), 0).clip(lower=0)

    # threshold = min age at license + years since license, also ≥ global min
    threshold = np.maximum(min_age_global, min_age_at_license + yrs_since_lic)

    # fix only if missing or below threshold
    fixed = age.copy()
    needs_fix = age.isna() | (age < threshold)
    fixed[needs_fix] = threshold[needs_fix]

    # clip and round to whole years
    fixed = fixed.clip(lower=min_age_global, upper=max_age_global).round().astype("Int64")
    return fixed.rename(out_col)

In [45]:
#df_all["t0_age_t_fixed_emp"] = fix_therapist_age_simple(
#    df_all,
#    age_col="t0_age_t",
#    license_year_col="t0_license_t",
#    reg_date_col="u_registrationDate_t",
#    min_age_at_license=29,   # set manually
#    min_age_global=23
#)

### Data exploration

In [46]:
df_all.to_csv(DATA_PATH + "/toni_preprocessed.csv")

### 2.2 Run Model

In [47]:
# Explainable Boosting Machone

In [48]:
from ML_Pipeline_CLEAR import MatchConfig, run_pipeline

cfg = MatchConfig(
    PATIENT_ID_COL="patient_id",
    THERAPIST_ID_COL="therapist_id",
    DATE_COL="u_registrationDate_p",
    DATE_DAYFIRST=True,
    DATE_FORMAT=None,

    LABEL_COL="t1_distress_sum",
    STANDARDIZE_Y=True,

    CAT_USE_NATIVE_CATEGORICAL=True,
    CAT_MIN_FREQ_FOR_OHE=1,

    # IMPORTANT: only keep these if they actually exist in your MatchConfig
    # TARGET_MODE="t1",
    # SCORING_MODE="rmse",

    patient_numeric = [
    't0_ses_p','surveys.t0.answers.1585.discrimination_1','surveys.t0.answers.1585.discrimination_2',
    'surveys.t0.answers.1585.discrimination_3','surveys.t0.answers.1585.discrimination_4','surveys.t0.answers.1585.discrimination_5',
    't0_phq_p_1','t0_phq_p_2','t0_phq_p_3','t0_phq_p_4','t0_phq_p_5','t0_phq_p_6','t0_phq_p_7','t0_phq_p_8',
    't0_gad_p_1','t0_gad_p_2','t0_gad_p_3','t0_gad_p_4','t0_gad_p_5','t0_gad_p_6','t0_gad_p_7',
    't0_swls_p_1','t0_swls_p_2','t0_swls_p_3','t0_swls_p_4','t0_swls_p_5',
    't0_aqol_p_1','t0_aqol_p_2','t0_aqol_p_3','t0_aqol_p_4','t0_aqol_p_5','t0_aqol_p_6','t0_aqol_p_7','t0_aqol_p_8','t0_aqol_p_9','t0_aqol_p_10',
    't0_aqol_p_11','t0_aqol_p_12','t0_aqol_p_13','t0_aqol_p_14','t0_aqol_p_15','t0_aqol_p_16','t0_aqol_p_17',
    't0_aqol_p_18','t0_aqol_p_19','t0_aqol_p_20','t0_aqol_p_21','t0_aqol_p_22','t0_aqol_p_23','t0_aqol_p_24','t0_aqol_p_25','t0_aqol_p_26',
    't0_aqol_p_27','t0_aqol_p_28','t0_aqol_p_29','t0_aqol_p_30','t0_aqol_p_31','t0_aqol_p_32','t0_aqol_p_33','t0_aqol_p_34','t0_aqol_p_35',
    't0_audit_p_1','t0_audit_p_2','t0_audit_p_3',
    't0_dudit_p_1','t0_dudit_p_2','t0_dudit_p_3','t0_dudit_p_4',
    't0_msfq_p_1','t0_msfq_p_2','t0_msfq_p_3','t0_msfq_p_4','t0_msfq_p_5',
    't0_pid_p_1','t0_pid_p_2','t0_pid_p_3','t0_pid_p_4','t0_pid_p_5','t0_pid_p_6','t0_pid_p_7','t0_pid_p_8','t0_pid_p_9','t0_pid_p_10',
    't0_pid_p_11','t0_pid_p_12','t0_pid_p_13','t0_pid_p_14','t0_pid_p_15','t0_pid_p_16','t0_pid_p_17','t0_pid_p_18','t0_pid_p_19','t0_pid_p_20',
    't0_pid_p_21','t0_pid_p_22','t0_pid_p_23','t0_pid_p_24','t0_pid_p_25','t0_pid_p_26','t0_pid_p_27','t0_pid_p_28','t0_pid_p_29','t0_pid_p_30',
    't0_pid_p_31','t0_pid_p_32','t0_pid_p_33','t0_pid_p_34','t0_pid_p_35','t0_pid_p_36',
    't0_opd_p_1','t0_opd_p_2','t0_opd_p_3','t0_opd_p_4','t0_opd_p_5','t0_opd_p_6','t0_opd_p_7','t0_opd_p_8','t0_opd_p_9','t0_opd_p_10','t0_opd_p_11','t0_opd_p_12',
    't0_ace_p_1','t0_ace_p_2','t0_ace_p_3','t0_ace_p_4','t0_ace_p_5','t0_ace_p_6','t0_ace_p_7','t0_ace_p_8','t0_ace_p_9','t0_ace_p_10',
    't0_ask_p_1','t0_ask_p_2','t0_ask_p_3',
    't0_mhse_p_1','t0_mhse_p_2','t0_mhse_p_3','t0_mhse_p_4','t0_mhse_p_5','t0_mhse_p_6',
    't0_change_p_1','t0_change_p_2','t0_dropout_p',
    't0_phq8_p_sum','t0_gad7_p_sum','t0_swls_p_sum',
    't0_aqol_p_coping','t0_aqol_p_relationship','t0_aqol_p_independent_living','t0_aqol_p_mental_health',
    't0_aqol_p_pain','t0_aqol_p_self_worth','t0_aqol_p_happiness','t0_aqol_p_senses',
    't0_audit_p_sum','t0_dudit_p_sum','t0_msfq_p_sum',
    't0_pid_p_negative_affect','t0_pid_p_antagonism','t0_pid_p_disinhibition','t0_pid_p_detachment','t0_pid_p_psychoticism','t0_pid_p_anankastia',
    't0_opd_p_self','t0_opd_p_contact','t0_opd_p_relationship',
    't0_ace_p_sum','t0_ask_p_sum','t0_mhse_p_sum','t0_age_p'
    ],
    patient_categorical = [
        't0_gender_p','t0_school_p','t0_employment_p','t0_location_p',
        't0_therapy_p_1','t0_therapy_p_2','t0_familyhistory_p','t0_meds_p',
        't0_relationship_p','t0_migration_p_1','t0_migration_p_2','t0_migration_p_3',
        't0_disease_p_A','t0_disease_p_B','t0_disease_p_C','t0_disease_p_D',
        't0_disease_p_E','t0_disease_p_F','t0_disease_p_G',
    ],
    therapist_numeric = [
        't0_age_t','t0_experience_t','t0_bfi_t_1','t0_bfi_t_2','t0_bfi_t_3','t0_bfi_t_4','t0_bfi_t_5',
        't0_bfi_t_6','t0_bfi_t_7','t0_bfi_t_8','t0_bfi_t_9','t0_bfi_t_10',
        't0_bfi_t_extraversion','t0_bfi_t_agreeableness','t0_bfi_t_conscientiousness',
        't0_bfi_t_neuroticism','t0_bfi_t_openness'
    ],
    therapist_categorical = [
        't0_method_t_CBT','t0_method_t_PDT','t0_method_t_ST','t0_method_t_AP',
        't0_appliedmethod_t_VT','t0_appliedmethod_t_TP','t0_appliedmethod_t_AP',
        't0_appliedmethod_t_ST','t0_appliedmethod_t_Other',
        't0_location_t','t0_gender_t','t0_relationship_t','t0_sexualorientation_t','t0_children_t'
    ], 

    EXPLAIN_COMPUTE_SHAP_GLOBAL=False,
    EXPLAIN_COMPUTE_SHAP_INTERACTIONS=False,
)

In [ ]:
results = run_pipeline(df_all, cfg)
results["summary"]

2026-01-30 09:54:15,268 [INFO] Match_Pipeline: date: parsing 'u_registrationDate_p' (dayfirst=True, format=None)
2026-01-30 09:54:15,496 [INFO] Match_Pipeline: Therapists: 174 | Train: 797 | Val: 0 | Test: 159 | repeat=0 | CV=outer_leave_last_inner_repeated
2026-01-30 09:54:15,499 [INFO] Match_Pipeline: candidates: 174 therapists in train
2026-01-30 09:54:15,503 [INFO] Match_Pipeline: ================================================================================
2026-01-30 09:54:15,503 [INFO] Match_Pipeline: [INNER CV] Using RepeatedPerTherapistHoldoutCV for HPO (nested strategy).
2026-01-30 09:54:15,504 [INFO] Match_Pipeline: [INNER CV] outer_train_n=797 | therapists=174
2026-01-30 09:54:15,504 [INFO] Match_Pipeline: [INNER CV] repeats=5 | val_per_therapist=1 | min_n_for_val=1 | fallback_global_val_frac=0.100 | base_seed=123
2026-01-30 09:54:15,504 [INFO] Match_Pipeline: ================================================================================
Fitting 5 folds for each of 12 candidates, totalling 60 fits
2026-01-30 09:54:15,765 [INFO] Match_Pipeline: [INNER CV] repeat=00 | train_n=655 | val_n=142 | train_therapists=174 | val_therapists=142
2026-01-30 09:54:15,770 [INFO] Match_Pipeline: [INNER CV] repeat=01 | train_n=655 | val_n=142 | train_therapists=174 | val_therapists=142
2026-01-30 09:54:15,775 [INFO] Match_Pipeline: [INNER CV] repeat=02 | train_n=655 | val_n=142 | train_therapists=174 | val_therapists=142
2026-01-30 09:54:15,780 [INFO] Match_Pipeline: [INNER CV] repeat=03 | train_n=655 | val_n=142 | train_therapists=174 | val_therapists=142
2026-01-30 09:54:15,785 [INFO] Match_Pipeline: [INNER CV] repeat=04 | train_n=655 | val_n=142 | train_therapists=174 | val_therapists=142
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.1min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.1min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.3min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 2.5min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.5min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 4.6min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 3.5min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 4.9min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 4.0min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 4.5min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 6.6min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 4.9min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.8min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 4.3min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 6.0min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 3.2min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 5.8min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 3.7min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 3.7min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=8, regressor__regressor__lr=0.0005, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=1e-05; total time= 4.1min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=16, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.6min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=16, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.4min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=16, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 5.2min
[CV] END regressor__regressor__batch_size=256, regressor__regressor__k=16, regressor__regressor__lr=0.001, regressor__regressor__n_epochs=40, regressor__regressor__weight_decay=0.0; total time= 3.7min